---
title: "QTM 150"
subtitle: "Week 3 -- R Basics II <html><div style='float:left'></div><hr color='#f2a900' size=1px width=800px></html>"
author: "Umberto Mignozzetti"
date: "Feb 12"
output: 
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    nature: 
      beforeInit: "https://raw.githubusercontent.com/umbertomig/qtm151/main/slides/wmisc/macros.js"
      highlightStyle: github
      ratio: 4:3
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
r <- getOption("repos")
r["CRAN"] <- "http://cran.cnr.berkeley.edu/"
options(repos = r)
```

<style>

.remark-slide-number {
  position: inherit;
}

.remark-slide-number .progress-bar-container {
  position: absolute;
  bottom: 0;
  height: 6px;
  display: block;
  left: 0;
  right: 0;
}

.remark-slide-number .progress-bar {
  height: 100%;
  background-color: #f2a900;
}

.orange {
  color: #f2a900;
}
</style>
# Recap

.font150[

* Last class you learned a lot!

* Difference between R and R Studio

* Calculations with R

* Variables and vectors

* R syntax

* **Great job!!**

]

---

# Today's Agenda

.font150[

* Sequences and Repetitions.

* Vectors.

* Functions and arguments.

* Matrices.

* R Studio shortcuts.

]

---

class: inverse, center, middle

# Sequences and Repetitions

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Sequences and Repetitions

.font150[
* We can also create vectors with sequences and repetitions.

* Sequences can be built with `:` or the function `seq`.

* Repetitions can be built with the function `rep`.

* **Your turn**: Compute the average of the following numbers: `r 1:6`. Save them in an object called `my_numbers`, but create them with sequences. Then, use the function `mean()`.

]

---

class: inverse, center, middle

# Vectors

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Vectors

.font150[
* Creating vectors.

* Length of vectors.

* Extract element from a vector:
  + Displaying specific elements.
  + Extract multiple elements.
  + Extract elements in sequence.
  + Not displaying given elements.

* **Your turn**: From the following vector: `y <- rnorm(10)`, (i) select the 3rd element; (ii) now the 4th until the 8th; (iii) all but the 9th.

]

---

class: inverse, center, middle

# Functions and Arguments

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Functions and Arguments

.font130[
* R has built in functions that we can use to do stats. Syntax:

```
r_function(arg1, arg2, ...)
```

* Let's try a few:
  + mean()
  + median()
  + sd()
  + max()
  + min()
  + summary()

* **Your turn**: Try the functions in the following vector: `m <- rnorm(1000)`.

]

---

class: inverse, center, middle

# Matrices

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Matrices

.font130[
* Creating matrix.

* Dimension of matrix.

* Extracting and changing elements:
  + Displaying columns.
  + Displaying rows.
  + Extracting one element.
  + Extract multiple elements.
  + Extract elements in sequence.

* **Your turn**: From the following vector: `m <- matrix(rnorm(9), nrow = 3)`, (i) select the 3rd row; (ii) select the second column; (iii) all but the second row.

]

---

class: inverse, center, middle

# R Scripts

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# R Scripts

.font150[
* What are R Scripts?

* How to create and save them.

* Running commands.

* Writing comments.

* **Your turn**: Create one script called `my_script.R`. Make one comment, create one vector, and take the mean of the vector.

]

---

class: inverse, center, middle

# Questions?

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

class: inverse, center, middle

# Have a great weekend!

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html>