---
title: "QTM 150"
subtitle: "Week 2 -- R Basics I <html><div style='float:left'></div><hr color='#f2a900' size=1px width=800px></html>"
author: "Umberto Mignozzetti"
date: "Feb 05"
output: 
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    nature: 
      beforeInit: "https://raw.githubusercontent.com/umbertomig/qtm151/main/slides/wmisc/macros.js"
      highlightStyle: github
      ratio: 4:3
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
r <- getOption("repos")
r["CRAN"] <- "http://cran.cnr.berkeley.edu/"
options(repos = r)
```

<style>

.remark-slide-number {
  position: inherit;
}

.remark-slide-number .progress-bar-container {
  position: absolute;
  bottom: 0;
  height: 6px;
  display: block;
  left: 0;
  right: 0;
}

.remark-slide-number .progress-bar {
  height: 100%;
  background-color: #f2a900;
}

.orange {
  color: #f2a900;
}
</style>
# Today's Agenda

.font150[

* DataCamp.

* Why is it so hard to program?

* Getting Started with R and R Studio.

* Computations with R.

* Working with Vectors.

* Functions and Arguments.

]

---

class: inverse, center, middle

# DataCamp

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# DataCamp

.font130[
* We partnered with DataCamp to provide you the first two R classes.

* These classes are going to teach you the very basics.

* The advantage of DataCamp, in these first days, is that you don't need to have R in your machine to get started

* Let's check my DataCamp?!

]
---

class: inverse, center, middle

# Questions?

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Why is it so hard to program?

.font130[
* Can you read this sentence: 4 exampel in Ingli$h you kin get prackicly evRiThing rong-rong-rong and sti11 be undr3stud.

* You can do it because English is a Natural language.

* R, Python, and other programming languages are formal languages.

* This means that you should pass the exact instructions for the computer to it do what you want to get done.

* Learning how to program is to learn how to speak a very formal language with a thing that doesn't understand informal writing.

* In this sense, as with learning any language, practice makes it perfect!

]

---

# Why is it so hard to program?

.font130[
* To understand R, you have to learn the syntax of the program.

* In the beginning, it is going to be hard. Then, with practice, you will see that there is a logic behind the program.

* This will be equivalent to fluency in a language: you will be able to strategize your coding even when you don't exactly know what to do.

* In my own experience, it took me around two months to become familiar with most of the rules.

]

---

# R and R Studio

.font150[
* R is the programming language that we are studying here.

* You probably by now googled R and know its history and how widely it is used.

* R Studio is **not** R! It is an Integrated Development Environment. Sort of a nice front-end to R.

* Let's check out R and R Studio!

]

---

# R and R Studio

.font150[
* Source editor x console.

* Files and working directory.

* Packages: expanding our R.

* How to get help?

]

---

class: inverse, center, middle

# Questions?

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# R as a Calculator

.font150[
* We can use R as a fancy calculator

* Check out the operations: `+`, `-`, `*`, `/`, `^`, `%%`, `%/%`.

* Creating and operating with variables. Syntax:

```
  var <- things_I_want_here
```

* **Your turn**: Compute the average of the following numbers: `r 1:6`

]

---

# R as a Calculator

.font150[
* In R, as in all other computer languages, we `do things` with `stuff`.

* The variables that we created are the `stuff`.

* The operations and functions are the ways that we `do things` with the variables.

* The `stuff` in R we call **objects**. In DataCamp, you will learn the most common.

]

---

class: inverse, center, middle

# Questions?

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Variables and Vectors

.font130[
* Vectors are collections of numbers.

* We use the function `c(.)` in R to put them together.

* Let's create some vectors in R.

* To do things in R (apply functions), we need to understand how they work.

* The syntax for functions is:

```
  func(arg1, arg2, ...)
```

* **Your turn**: Compute the average of the following numbers: `r 1:6`. But now, save them in an object called `my_numbers` and use the function `mean()`.

]

---

# Sequences and Repetitions

.font150[
* We can also create vectors with sequences and repetitions.

* Sequences can be built with `:` or the function `seq`.

* Repetitions can be built with the function `rep`.

* **Your turn**: Compute the average of the following numbers: `r 1:6`. Save them in an object called `my_numbers`, but create them with sequences. Then, use the function `mean()`.

]

---

class: inverse, center, middle

# Questions?

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

class: inverse, center, middle

# Have a great weekend!

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html>