---
title: "QTM 150"
subtitle: "Class 2 -- R Basics <html><div style='float:left'></div><hr color='#f2a900' size=1px width=800px></html>"
author: "Umberto Mignozzetti"
date: "Summer"
output: 
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    nature: 
      beforeInit: "https://raw.githubusercontent.com/umbertomig/qtm151/main/slides/wmisc/macros.js"
      highlightStyle: github
      ratio: 4:3
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
r <- getOption("repos")
r["CRAN"] <- "http://cran.cnr.berkeley.edu/"
options(repos = r)
```

<style>

.remark-slide-number {
  position: inherit;
}

.remark-slide-number .progress-bar-container {
  position: absolute;
  bottom: 0;
  height: 6px;
  display: block;
  left: 0;
  right: 0;
}

.remark-slide-number .progress-bar {
  height: 100%;
  background-color: #f2a900;
}

.orange {
  color: #f2a900;
}
</style>
# Today's Agenda

.font150[

* How R works?

* Working with Vectors.

* Functions and Arguments.



* Datasets

* R Markdown.

]

---

class: inverse, center, middle

# How R Works?

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# How R Works?

.font130[
R is a **statistical programming language.**

**Programming language**: different from point-and-click applications: 
* We *talk to the computer* in a way closer to what the computer understands.

**Statistical**: most of the functions and methods are suited to statistical analysis.

]

---

# Why is it so hard to program?

.font130[
* Can you read this sentence: 4 exampel in Ingli$h you kin get prackicly evRiThing rong-rong-rong and sti11 be undr3stud.

* You can do it because English is a Natural language.

* R, Python, and other programming languages are formal languages.

* This means that you should pass the exact instructions for the computer to it do what you want to get done.

* Learning how to program is to learn how to speak a very formal language with a thing that doesn't understand informal writing.

* In this sense, as with learning any language, practice makes it perfect!

]

---

# R as a Calculator

.font150[
We can use R as a fancy calculator

Check out the operations: `+`, `-`, `*`, `/`, `^`, `%%`, `%/%`.

Creating and operating with variables. Syntax:

```
var <- things_I_want_here
```

* **Your turn**: Compute the average of the following numbers: `r 1:6`

]

---

# R as a Calculator

.font150[
* In R, as in all other computer languages, we `do things` with `stuff`.

* The variables that we created are the `stuff`.

* The operations and functions are the ways that we `do things` with the variables.

* The `stuff` in R we call **objects**. In DataCamp, you will learn the most common.

]

---

class: inverse, center, middle

# Variables, Vectors, and Functions

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Variables and Vectors

.font130[
Vectors are collections of numbers or strings.

We use the function `c(.)` in R to put them together.

Let's create some vectors in R.

To do things in R (apply functions), we need to understand how they work.

The syntax for functions is:

```
func(arg1, arg2, ...)
```

* **Your turn**: Compute the average of the following numbers: `r 1:6`. But now, save them in an object called `my_numbers` and use the function `mean()`.

]


---

# Functions and Arguments

.font130[
* R has built in functions that we can use to do stats. Syntax:

```
r_function(arg1, arg2, ...)
```

* Let's try a few:
  + mean()
  + median()
  + sd()
  + max()
  + min()
  + summary()

* **Your turn**: Try the functions in the following vector: `m <- rnorm(1000)`.

]

---

class: inverse, center, middle

# Matrices

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Matrices

.font130[
* Creating matrix.

* Dimension of matrix.

* Extracting and changing elements:
  + Displaying columns.
  + Displaying rows.
  + Extracting one element.
  + Extract multiple elements.
  + Extract elements in sequence.

* **Your turn**: From the following vector: `m <- matrix(rnorm(9), nrow = 3)`, (i) select the 3rd row; (ii) select the second column; (iii) all but the second row.

]

---

class: inverse, center, middle

# Datasets

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# Datasets

.font130[
* We can use many functions to get to know our datasets:
  - `names(data_set_here)`
  - `dim(data_set_here)`
  - `summary(data_set_here)`
  - `str(data_set_here)`
  - `head(data_set_here)`

* **Your turn**: Load a dataset called USArrests and explore it. Hint: to load this dataset you should do `data(USArrests)`. To learn about it you should run `help(USArrests)`.

]

---

# Working with datasets

.font130[
* We can also build some simple plots:
  - `hist(data_set_here$variable_here)`
  - `boxplot(data_set_here$variable_here)`
  - `plot(data_set$variable_here, data_set$other_var)`

* **Your turn**: Make a few plots of the dataset **USArrests**.

]

---

class: inverse, center, middle

# R Markdown

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

# R Markdown

.font150[
* R Markdown is a way to integrate computer and stats coding with text.

* These slides that you are seeing now were build using *R Markdown*!

* Let's check out my R Markdown?

* **Your turn**: build one R markdown. Using the default template, change your name, add one paragraph, and make one extra plot than the one in the default.
]

---

class: inverse, center, middle

# Questions?

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html> 

---

class: inverse, center, middle

# See you next class!

<html><div style='float:left'></div><hr color='#f2a900' size=1px width=720px></html>